#!/bin/busybox sh

# Mount filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# Setup dhcp
ip link set eth0 up
udhcpc

# Open shell
setsid cttyhack sh

# Unmount filesystems
umount /proc
umount /sys
umount /dev

# Reboot on exit
echo "Shell exited, rebooting..."
sleep 5
exec /bin/busybox reboot -f

# Boot the real thing.
#exec switch_root /mnt/root /sbin/init
