#!/bin/sh

IMAGE="flatcar_production_iso_image.iso"

# Mount filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# Create directories
mkdir /mnt/iso
mkdir /mnt/root

# Setup dhcp
ip link set eth0 up
udhcpc

# Download and unpack image
curl -O -k https://syno.lan:8443/${IMAGE}
mount -o loop ${IMAGE} /mnt/iso
cp -a /mnt/iso/* /mnt/root

# Unmount filesystems
umount /proc
umount /sys
umount /dev

clear

# Boot the real thing.
exec switch_root /mnt/root /sbin/init
